### ISSUE TITLE
Manually pass the log level

### ISSUE THREAD

**Issue by corbinu** [kkamkou/node-gelf-pro#15]
I am writing a [good](https://github.com/hapijs/good) plugin using gelf pro.

I was wondering if you would be open to an option to manually pass the log level. (I am happy to submit a PR) 

As hapi logs don't map directly to syslog error levels I want to give the user an option to configure based on the log 'event' and 'tags' [doc](http://hapijs.com/api#server-events) what level should be used.

**Comment by kkamkou** [comment]
Hi Corbin! Yes, sure, we can think about it. But, please, fix tests first.

**Comment by corbinu** [comment]
Ok any idea why sinon would break as I showed on the first few it isn't that the code isn't working appears to be some failure in sinon

**Comment by kkamkou** [comment]
[should be](https://github.com/corbinu/node-gelf-pro/blob/message_with_lvl/lib/gelf-pro.js#L184) `this`, we're in the gelf context already.

**Comment by corbinu** [comment]
Should be all set thanks.

**Comment by kkamkou** [comment]
Merged, thank you. Keep contributing!
