### ISSUE TITLE
TypeScript definitions are outdated

### ISSUE THREAD

**Issue by kkamkou** [kkamkou/node-gelf-pro#30]
Some functionality is not covered.

**Comment by kkamkou** [comment]
@jucrouzet could you take over this ticket and update the definition file?

**Comment by jucrouzet** [comment]
Yep, I'lll have a look tomorrow

**Comment by iamvijaydev** [comment]
Adding a find here:

Definition for `broadcast` is set as `EventListener[]`, [link](https://github.com/kkamkou/node-gelf-pro/blob/159e2d4c6487b3fb042cabcf582308cca91ec60c/lib/definition.d.ts#L43). Type EventListener is only available for [webworker](https://github.com/Microsoft/TypeScript/blob/49a48ffd4d7ed76fa4033752d1d55a1ad31ab18a/lib/lib.webworker.d.ts#L150-L152). Meaning a project that uses this lib, should in its `tsconfig.js`, include webworker as following
```javascript
{
  "compilerOptions": {
    "lib": [
      "es2016",
      "webworker"
    ]
}
```

I am not completely sold on specifying webworker as a compilation lib when I don't use in the project itself. Could we change the definition as `Function[]`

**Comment by kkamkou** [comment]
I'm not working with the typescript right now. Any person who would like to add the support, please create a new PR. Thank you.

Outdated definitions have been removed via 4a36609a29b4f85649c4190303aa52afcdbd2a61
