### ISSUE TITLE
My graylog2 server not receiving any log whn using node-gelf-pro

### ISSUE THREAD

**Issue by HarisHashim** [kkamkou/node-gelf-pro#32]
```
  var grayLog = require("gelf-pro");
  grayLog.setConfig({
    adapterName: "tcp",
    timeout: 1000,
    host: "192.168.0.102",
    port: 12203,
    family: 4
  });

// ... later

 const data = { label: "label", message: "DONE", duration: 123 };
  grayLog.info(JSON.stringify(data) + "\x00");

```

I know my server and configuration is working because I call bellow from shell and it works since I can see log added to the input.

```
echo -e '{"label":"get_user","message":"DONE","duration":123.2}\x00' | netcat -w 1 localhost 12203
```

TIA

**Comment by kkamkou** [comment]
The library adds `\x00` for you. Just omit it.

**Comment by HarisHashim** [comment]
@kkamkou  thanks for the quick reply

Actually I put the null terminator string to troubleshoot. Without it and indeed I just copy your exact code and retry. Still not working.

```
grayLog.info('DONE', {label: 'label', duration: 123});
```

If it is not the null terminator, then must be something wrong with my config. 

Will look into this again later as I am doing some other work around using net.socket at the moment that is working.

```
    socket.connect(PORT, HOST, function() {
      debug("CONNECTED TO: %s:%s. Sending profiling data: %j",HOST,PORT, data);
      socket.write(JSON.stringify(data) + "\x00");
      socket.end();
    });
```
