### ISSUE TITLE
UDP adapter max chunks count

### ISSUE THREAD

**Issue by essentia0** [kkamkou/node-gelf-pro#38]
Hi,

I've come to an issue about the maximum number of chunks using UDP adapter.

The [code](https://github.com/kkamkou/node-gelf-pro/blob/2e535ff72906a66c6c9aff2282a02545b592f85f/lib/adapter/udp.js#L28) limits it to 20 but the [documentation](http://docs.graylog.org/en/2.4/pages/gelf.html#chunking) suggests a maximum of 128. 

Is there any reason for that limit not following the specs ?

**Comment by kkamkou** [comment]
Thank you for the update. Nope, 20 was a random number most probably I've linked it with ES indexes count that time (`20`).
