### ISSUE TITLE
Message Length clarification

### ISSUE THREAD

**Issue by rosygupta** [kkamkou/node-gelf-pro#40]
Hi @kkamkou ,

With regards to my previous question in #24, is `32766 bytes` the graylog recommended `maxlength` for a field in a message? Can you direct me to the documentation link if it is so?

**Comment by kkamkou** [comment]
It is limitation of the Lucene index (elasticsearch). Here is some tips to avoid it:
https://github.com/Graylog2/graylog2-server/issues/873
