### ISSUE TITLE
plain object -> readable format

### ISSUE THREAD

**Issue by rosygupta** [kkamkou/node-gelf-pro#42]
Hi,
Is there a way to turn off this capability to convert a plain object into readable format?
I mean this one:
`log.info(
  'a new msg goes here',
  {me: {fname: 'k', lname: 'k', bdate: new Date(2000, 01, 01)}}
);
// ^-- extra becomes: {_me_fname: 'k', _me_lname: 'k', _me_bdate: 'Tue Feb 01 2000 00:00:00 GMT+0100 (CET)'}`

**Comment by kkamkou** [comment]
What is the expectations? Could you provide some examples?

**Comment by rosygupta** [comment]
I want to dump the whole object into graylog as it is. I assume that this capability to convert a plain object was added to the library to enhance the search in graylog. But if I do this, the number of fields in my index increases drastically and leads to index failure. Only 1000 fields are allowed in 1 index.

**Comment by kkamkou** [comment]
> I want to dump the whole object into graylog as it is.

You can't do that (elasticsearch is typed(Double/Long/etc.) and node.js is not). Though, you may try to use [JSON.stringify](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify). If the object is huge, try to `stringify` the second level only and so on.

**Comment by rosygupta** [comment]
This library allows me to do that. https://www.npmjs.com/package/graylog2

 The screenshot shows it.  The first log with field "full_message"

![screenshot from 2018-04-18 18-47-52](https://user-images.githubusercontent.com/6587993/38934320-18712e1e-4339-11e8-9c0e-4cbf32cc89da.png)

**Comment by kkamkou** [comment]
`log.info(JSON.stringify({me: {fname: 'k', lname: 'k', bdate: new Date(2000, 01, 01)}}))` does the same. If you need primitives, I think that library might suit you better.

**Comment by rosygupta** [comment]
Yea I get it. Btw, toString() doesn't work.
