### ISSUE TITLE
Delays releasing UDP port on DNS timeout.

### ISSUE THREAD

**Issue by jeremy-j-ackso** [kkamkou/node-gelf-pro#46]
I discovered this because of a very chatty service using this library running my server out of available ports to send messages to Graylog.

I'm not sure of a good way to reproduce this issue or test for it, but the errors that I run into are:

```
null: 'uncaughtException called: Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data'
{{my error callback}}
{ Error: getaddrinfo EAI_AGAIN {{my graylog host}}
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: '{{my graylog host}}' }
```

I believe that it may be the result of the callback to `async.waterfall` calling `send`'s callback not as a result of `client.close()`.

PR incoming.

**Comment by kkamkou** [comment]
Hi Jeremy, thank you for the ticket (and PR attempt). I've released a new version mostly because of this issue. I hope it'll fix it. Please test and re-open the ticket if needed. Thank you!

Resolved via: 4a36609a29b4f85649c4190303aa52afcdbd2a61
