### ISSUE TITLE
Can I use multiple GELF configurations?

### ISSUE THREAD

**Issue by natesilva** [kkamkou/node-gelf-pro#49]
Is it possible to have multiple logger instances? Each one would connect to a different Graylog server and have its own configuration.

From my reading of the source code it looks like the logger object is a singleton.

**Comment by kkamkou** [comment]
In tests, for example, `_.cloneDeep` is [used](https://github.com/kkamkou/node-gelf-pro/blob/master/test/tests.js#L34) to create multiple instances. I assume you could do it like this: 
```
const _ = require('lodash');
const prototype = require('gelf-pro');
const gelf1 = _.cloneDeep(prototype),
  gelf2 = _.cloneDeep(prototype);
```
Please let me know if it works for you.

**Comment by natesilva** [comment]
Aha. Thanks!
