### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by Manikanta-20** [kkamkou/node-gelf-pro#59]
It will support  react/next.js/gatsby

**Comment by kkamkou** [comment]
Feel free to contribute. that is MIT library.

**Comment by Manikanta-20** [comment]
@kkamkou I'll try to contribute on this

**Comment by Manikanta-20** [comment]
@kkamkou                                                  what I have requested  compatibility requirement / CR is belong to frontend?

I will work on this requirement could you assign to me and reopen

**Comment by kkamkou** [comment]
You can also check this project: https://www.npmjs.com/package/gelfjs

**Comment by Manikanta-20** [comment]
Thanks @kkamkou 

This feature I will contribute on gelfjs repo
 
first  I will work on react and next.js ...after that we can provide this feature for angular/ vue/ etc
