### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by r3econ** [kkamkou/node-gelf-pro#66]
Is it possible to use `node-gelf-pro` with Angular? I am getting the following errors when I compile the project after following the installation guide.

```
ERROR in ./node_modules/gelf-pro/lib/adapter/udp.js
Module not found: Error: Can't resolve 'dgram' in '.../node_modules/gelf-pro/lib/adapter'
ERROR in ./node_modules/gelf-pro/lib/adapter/tcp.js
Module not found: Error: Can't resolve 'net' in '.../node_modules/gelf-pro/lib/adapter'
ERROR in ./node_modules/gelf-pro/lib/adapter/tcp-tls.js
Module not found: Error: Can't resolve 'tls' in '.../node_modules/gelf-pro/lib/adapter'
```

I tried manually installing e.g. `dgram` but the error still persists.

**Comment by kkamkou** [comment]
`node-gelf-pro` is for node.js. Please look for other libraries*.

\* - for angular+typescript you could try my pet project:
https://github.com/kkamkou/gelfjs and https://kkamkou.gitbook.io/gelf-js/configuration (advanced tab).
