### ISSUE TITLE
socket reuse

### ISSUE THREAD

**Issue by npomfret** [kkamkou/node-gelf-pro#67]
We have a very busy system and use a TCP connection to graylog.  We're starting to see errors relating to open file handles and it seems that we have several thousand sockets open to our graylog server.  I was wondering why this TCP adapter doesn't reuse the socket?  Why would you need more than one?

**Comment by npomfret** [comment]
I ended up forking to see if socket resume works.   It seems fine:

https://github.com/kkamkou/node-gelf-pro/pull/68

**Comment by kkamkou** [comment]
This is rather complicated topic (refs #24). I'll check the pr later on.

**Comment by kkamkou** [comment]
I've put a comment in the PR. Please have a look. According to the ticket, I would recommend to use udp adapter for an average to high-loaded project. UDP is pretty reliable nowadays. In case you transfer super important information, you might need another solution in general. Nevertheless, a new adapter is also an option.
