### ISSUE TITLE
Validation for a custom short_message field

### ISSUE THREAD

**Issue by Givemeurcookies** [kkamkou/node-gelf-pro#72]
Just wanted to my share my experience and suggest an improvement. It would be nice if the "message" parameter had type validation to make sure an object isn't passed in but only a string or error object. Because it's possible to pass in an error - I misunderstood the API documentation and thought it was possible to pass in an object. Since there's no type validation I ended up with this error (in case anyone googles this "bug") in Graylog but got no error from the node-gelf-pro library:
```
java.lang.IllegalArgumentException: GELF message <message_id> (received from <ip_address>) has invalid "short_message"
```
Type validation is also nice in case somone accidentally passes in an object (or different type) when they meant to pass in a string. How the codebase currently works that would cause a bug which would be very hard to detect since it would be "silent".

**Comment by kkamkou** [comment]
Could you share the code fragment. There is multiple validations. It looks like your error has no message inside (?)

**Comment by Givemeurcookies** [comment]
I will try my best to help reproduce the problem.

Only additional error data passed from the Graylog logs would be:
```
Unable to decode raw message RawMessage{id=<message_id>, messageQueueId=1545, codec=gelf, payloadSize=209, timestamp=2021-11-15T12:44:13.374Z, remoteAddress=/172.18.0.1:45070} on input <6191b57727ed8f243558a49d>.
```
I've replaced the message id and ip adress from the logs.

I have already worked around the problem and passed the object it into the "extra" parameter i.e `log.info("Hello world", extra);`

The first parameter ("Hello world") did not work by sending in anything else than a string. A simple object would not work.

I believe I also tried to simply pass in this object when trying to fix the issue, like so (code may need to be changed, it's just written from memory and not tested):
```
const message = {
  "version": "1.0",
  "host": "www1",
  "short_message": "Short message",
  "full_message": "Backtrace here\n\nmore stuff",
  "timestamp": Date.now() / 1000,
  "level": 1,
  "facility": "payment-backend",
  "file": "/var/www/somefile.rb",
  "line": 356,
  "_user_id": 42,
  "_something_else": "foo"
}
//  Second parameter was undefined because it was an undefined parameter in a inside a function
log.info(message, undefined);
```

Which did not work. If you're unable to reproduce the validation error, I will see if I rewrite some of my code to recreate the problem again so I can give you a code fragment.

**Comment by kkamkou** [comment]
It looks like you've used some kind of library before or just read the specification. That is not the case here. For example a number of fields have been deprecated; gelf pro does most of it for you. example:

```js
log.info('Short message', {full_message: "Backtrace here\n\nmore stuff", {something_else: "foo", user: {id: 1}}});
```

as simply as this. In your case it looks like you've put `short_message` and library takes your value as first priority
