### ISSUE TITLE
Typescript: Property 'info' does not exist on type 'typeof import("gelf-pro") ...

### ISSUE THREAD

**Issue by MarceloLuis1997** [kkamkou/node-gelf-pro#76]
Hello!

I am getting the error `Property 'info' does not exist on type 'typeof import("gelf-pro")'.` when importing this package:

```
import * as log from 'gelf-pro';

log.info('Hello world', { test: 123 }, function (err, bytesSent) { // Property 'info' does not exist....
    console.log('err, bytes', err, bytesSent);
});
```
However it works fine when I use it with `require`:
`const log = require('gelf-pro');`

How can I use it with `import`? It's a NestJS TS Application.

**Comment by kkamkou** [comment]
import typings: https://github.com/kkamkou/node-gelf-pro/blob/master/typings/index.d.ts
