### ISSUE TITLE
Unstable sending of chunked messages

### ISSUE THREAD

**Issue by RedMickey** [kkamkou/node-gelf-pro#80]
Hi, I faced a problem that sometimes Graylog cannot receive messages cut into chunks due to their size. I'm using a udp adapter to send logs, so at first I thought I had a network problem. But after investigating this issue I found out that it could be a race condition between sending chunks and closing the socket [here](https://github.com/kkamkou/node-gelf-pro/blob/master/lib/adapter/udp.js#L108-L122). I tested the issue on my local machine, so it's unlikely that I could have network problems.
I added `console.log` to the [callback](https://github.com/kkamkou/node-gelf-pro/blob/master/lib/adapter/udp.js#L117-L118) to check the order in which chunk ids were sent. Here are my logs:
- A message was sent successfully:
    ```
    chunkIdx 1
    chunkIdx 0
    chunkIdx 2
    chunkIdx 3
    chunkIdx 4
    chunkIdx 5
    ```
    or
    ```
    chunkIdx 0
    chunkIdx 1
    chunkIdx 2
    chunkIdx 3
    chunkIdx 4
    chunkIdx 5
    ```

- Failed to send a message
    ```
    chunkIdx 0
    chunkIdx 1
    chunkIdx 3
    chunkIdx 4
    chunkIdx 5
    ```
    or
    ```
    chunkIdx 1
    chunkIdx 0
    chunkIdx 2
    chunkIdx 3
    chunkIdx 5
    ```

So sending messages works asynchronously, and it's possible to send the last chunk (5) before a penultimate chunk (4) or some other. In the callback there is [the condition where we check if the last chunk has been sent ](https://github.com/kkamkou/node-gelf-pro/blob/master/lib/adapter/udp.js#L118) and then we [close the socket](https://github.com/kkamkou/node-gelf-pro/blob/master/lib/adapter/udp.js#L74-L75). So we can close the socket before all chunks have been sent.
Could it be that the socket close condition should be changed to avoid a race condition?

**Comment by kkamkou** [comment]
will be hard to unit test it. most probably you're right, will add the fix, kudo for the report

**Comment by RedMickey** [comment]
Thanks for the fix!
