### ISSUE TITLE
Http transport

### ISSUE THREAD

**Issue by DungTiger** [kkamkou/node-gelf-pro#95]
Hello,

We used to have the Tcp transport when our Graylog instance and the servers were in the same private network.
We're splitting things around and moving Graylog behind a reverse proxy and we need a Http transport implementation.

I'm willing to do the transport as part of the library, is this still maintained and accepts pull requests?

**Comment by kkamkou** [comment]
consider https://github.com/kkamkou/gelfjs, you can PR there
